=== milligan22963/PageBuilder/pageBuilder/paramManager.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema targetNamespace="http://www.afmsoftware.com/paramManager" elementFormDefault="qualified" xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:afm="http://www.afmsoftware.com/paramManager">
 <xs:complexType name="paramAttr">
 	<xs:attribute name="name" type="xs:string"></xs:attribute>
 	<xs:attribute name="required" type="xs:boolean"></xs:attribute>
 </xs:complexType>
 <xs:complexType name="paramSet">
	 <xs:sequence>
	 	<xs:element name="param" type="afm:paramAttr" maxOccurs="unbounded"/>
	 </xs:sequence>
 </xs:complexType>
 <xs:complexType name="commandType">
  <xs:sequence>
   	  <xs:element name="params" type="afm:paramSet" maxOccurs="unbounded"/>
    </xs:sequence>
 	<xs:attribute name="name" type="xs:string"></xs:attribute>
  </xs:complexType>
 <xs:complexType name="commandSet">
	 <xs:sequence>
	 	<xs:element name="command" type="afm:commandType" maxOccurs="unbounded"/>
	 </xs:sequence>
 </xs:complexType>
<xs:element name="commands" type="afm:commandSet"></xs:element>
</xs:schema>

=== milligan22963/PageBuilder/pageBuilder/commandparam.xml
<?xml version="1.0" encoding="UTF-8"?>
<afm:commands xmlns:afm="http://www.afmsoftware.com/paramManager" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.afmsoftware.com/paramManager paramManager.xsd ">
	<afm:command name="create">
		<afm:params>
			<afm:param name="id" required="false"/>
			<afm:param name="active" required="false"/>
		</afm:params>
	</afm:command>
	<afm:command name="modify">
		<afm:params>
			<afm:param name="id" required="true"></afm:param>
			<afm:param name="active" required="false"></afm:param>
		</afm:params>
	</afm:command>
	<afm:command name="delete">
		<afm:params>
			<afm:param name="id" required="true"></afm:param>
			<afm:param name="active" required="false"></afm:param>
		</afm:params>
	</afm:command>
	<afm:command name="activate">
		<afm:params>
			<afm:param name="id" required="true"></afm:param>
			<afm:param name="active" required="true"></afm:param>
		</afm:params>
	</afm:command>
	<afm:command name="view">
		<afm:params>
			<afm:param name="id" required="true"></afm:param>
			<afm:param name="active" required="false"></afm:param>
		</afm:params>
	</afm:command>
	<afm:command name="tag">
		<afm:params>
			<afm:param name="id" required="true"></afm:param>
		</afm:params>
	</afm:command>
</afm:commands>
