=== milligan22963/PageBuilder/pageBuilder/theme.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" targetNamespace="http://www.afmsoftware.com/theme" xmlns:afm="http://www.afmsoftware.com/theme" elementFormDefault="qualified">
 	<xs:complexType name="widgetFile">
	  <xs:simpleContent>
	    <xs:extension base="xs:string">
	      <xs:attribute name="display" type="xs:string" />
	    </xs:extension>
	  </xs:simpleContent>
	</xs:complexType>
	 <xs:complexType name="themeSet">
		 <xs:sequence>
		 	<xs:element name="name" type="xs:string" maxOccurs="1"/>
		 	<xs:element name="description" type="xs:string" maxOccurs="1"/>
		 	<xs:element name="stylesheet" type="xs:string" maxOccurs="1"/>
		 	<xs:element name="images" type="xs:string" maxOccurs="1"/>
		 	<xs:element name="javascript" type="xs:string" maxOccurs="1"/>
		 	<xs:element name="functions" type="xs:string" maxOccurs="1"/>
		 	<xs:element name="headerfile" type="xs:string" minOccurs="0" maxOccurs="1"/>
		 	<xs:element name="headerwidgetfile" type="afm:widgetFile" minOccurs="0" maxOccurs="1"/>
		 	<xs:element name="bodyfile" type="xs:string" minOccurs="0" maxOccurs="1"/>
		 	<xs:element name="bodywidgetfile" type="afm:widgetFile" minOccurs="0" maxOccurs="1"/>
		 	<xs:element name="footerfile" type="xs:string" minOccurs="0" maxOccurs="1"/>
		 	<xs:element name="footerwidgetfile" type="afm:widgetFile" minOccurs="0" maxOccurs="1"/>
		 </xs:sequence>
	 </xs:complexType>
	<xs:element name="theme" type="afm:themeSet"></xs:element>
</xs:schema>

=== milligan22963/PageBuilder/admin/theme/description.xml
<?xml version="1.0" encoding="UTF-8"?>
<p:theme xmlns:p="http://www.afmsoftware.com/theme" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.afmsoftware.com/theme ../../pageBuilder/theme.xsd ">
  <p:name>Admin</p:name>
  <p:description>The admin theme for this package</p:description>
  <p:stylesheet>default.css</p:stylesheet>
  <p:images>images</p:images>
  <p:javascript>js</p:javascript>
  <p:functions>themeulator.php</p:functions>  
  <p:headerfile>header.php</p:headerfile>
  <p:bodyfile>body.php</p:bodyfile>
  <p:bodywidgetfile display="post">body_wdg.php</p:bodywidgetfile>
  <p:footerfile>footer.php</p:footerfile>
  <p:footerwidgetfile display="post">footer_wdg.php</p:footerwidgetfile>
</p:theme>
