=== milligan22963/PageBuilder/install/install.xsd
<?xml version="1.0" encoding="ISO-8859-1"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
targetNamespace="http://www.afmsoftware.com"
xmlns="http://www.afmsoftware.com"
elementFormDefault="qualified">
 <xs:complexType name="tableAttr">
 	<xs:attribute name="name" type="xs:string"></xs:attribute>
 	<xs:attribute name="codefile" type="xs:string"></xs:attribute>
 	<xs:attribute name="version" type="xs:string"></xs:attribute>
 	<xs:attribute name="dependency" type="xs:string"></xs:attribute>
 </xs:complexType>
  <xs:complexType name="databaseType">
  <xs:sequence>
   	  <xs:element name="table" type="tableAttr" maxOccurs="unbounded"/>
    </xs:sequence>
 	<xs:attribute name="name" type="xs:string"></xs:attribute>
 	<xs:attribute name="codefile" type="xs:string"></xs:attribute>
 	<xs:attribute name="version" type="xs:string"></xs:attribute>
  </xs:complexType>
 <xs:complexType name="installType">
	 <xs:sequence>
	 	<xs:element name="database" type="databaseType" maxOccurs="unbounded"/>
	 </xs:sequence>
 </xs:complexType>
<xs:element name="install" type="installType"/>
</xs:schema>

=== milligan22963/PageBuilder/install/install.xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-stylesheet href="install.xsl" type="text/xsl" ?>
<p:install xmlns:p="http://www.afmsoftware.com" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.afmsoftware.com install.xsd ">
  <p:database name="ignore" codefile="database.php" version="1.0.0.0">
	  <p:table name="users" codefile="users.php" version="1.0.0.0" dependency="activity"/>
	  <p:table name="site" codefile="site.php" version="1.0.0.0" dependency="none"/>
	  <p:table name="email" codefile="email.php" version="1.0.0.0" dependency="users"/>
	  <p:table name="activity" codefile="activity.php" version="1.0.0.0" dependency="none"/>
	  <p:table name="extension" codefile="extension.php" version="1.0.0.0" dependency="none"/>
	  <p:table name="content" codefile="content.php" version="1.0.0.0" dependency="none" />
	  <p:table name="posts" codefile="posts.php" version="1.0.0.0" dependency="content" />
	  <p:table name="fonts" codefile="fonts.php" version="1.0.0.0" dependency="none" />
	  <p:table name="text" codefile="text.php" version="1.0.0.0" dependency="none" />
  </p:database>
</p:install>
